In [25]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [27]:
df.shape

(569, 33)

In [28]:

df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [29]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [30]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [31]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
X_train

array([[ 1.04268993,  0.93196997,  1.17233552, ...,  1.34843494,
        -0.98561375,  2.11744478],
       [ 2.64590556,  0.12777268,  2.57349869, ...,  1.76607249,
         0.03070843, -0.61057205],
       [-0.66857484, -1.20719482, -0.72240961, ..., -0.47015844,
         0.35385535, -0.93432823],
       ...,
       [-0.31522494, -0.74765351, -0.34566181, ..., -0.1164132 ,
         0.8209952 ,  0.65751878],
       [-0.48751952,  0.58042087, -0.48789468, ...,  0.11578082,
         0.13786596,  0.47997507],
       [-1.25846474, -0.24215807, -1.2943043 , ..., -1.76202982,
        -1.64195361, -1.00523578]])

In [33]:
y_train

468    M
503    M
281    B
260    M
351    M
      ..
552    B
374    B
292    B
88     B
192    B
Name: diagnosis, Length: 455, dtype: object

In [34]:
X_test

array([[ 0.43819879,  3.28252377,  0.52466795, ...,  1.37648522,
         1.04200761,  2.00751059],
       [-0.34150717, -1.36803428, -0.35920779, ...,  0.03786336,
        -0.8499925 ,  0.09080805],
       [-0.3123047 , -0.22607412, -0.30163734, ..., -0.73227275,
         0.53133501, -0.62706218],
       ...,
       [-1.35278872,  0.55284839, -1.33578889, ..., -1.36246912,
        -0.86003852,  0.44974317],
       [ 0.14617409,  0.01518506,  0.12463798, ..., -0.26694972,
        -0.70097656, -0.50833326],
       [-0.07576469, -1.37952281, -0.13739223, ..., -0.85787569,
        -0.11161016, -0.87606311]])

In [35]:
y_test

259    M
322    B
402    B
57     M
198    M
      ..
541    B
556    B
412    B
448    B
295    B
Name: diagnosis, Length: 114, dtype: object

In [36]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [37]:
X_train_ten=torch.from_numpy(X_train)
X_test_ten=torch.from_numpy(X_test)
y_train_ten=torch.from_numpy(y_train)
y_test_ten=torch.from_numpy(y_test)

In [38]:
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_train_ten:", X_train_ten.shape)
print("y_train_ten:", y_train_ten.shape)

X_train: (455, 30)
y_train: (455,)
X_train_ten: torch.Size([455, 30])
y_train_ten: torch.Size([455])

In [39]:
X_train_ten = X_train_ten.float()
X_test_ten = X_test_ten.float()

y_train_ten = y_train_ten.float()
y_test_ten = y_test_ten.float()

In [40]:
from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,index):

    return self.features[index],self.labels[index]

In [41]:
train_dataset=CustomDataset(X_train_ten,y_train_ten)
test_dataset=CustomDataset(X_test_ten,y_test_ten)

In [42]:
train_dataset.__getitem__(10)

(tensor([ 1.5304,  1.6534,  1.5491,  1.5365, -0.1591,  1.2782,  0.9817,  0.7271,
          0.1503, -0.0298,  0.5814, -1.0861,  0.3599,  0.6955, -0.7561,  0.4148,
          0.0848, -0.3490, -0.6279,  0.0189,  1.7323,  0.8532,  1.7125,  1.7811,
          0.8301,  2.5997,  1.6245,  1.0196,  1.3099,  1.5623]),
 tensor(1.))

In [43]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [44]:
#Defining the NN

In [45]:
import torch
import torch.nn as nn

# Defining Neural Network
class SimpleNN(nn.Module):

  def __init__(self,num_features):

   super().__init__()
   self.linear=nn.Linear(num_features,1)
   self.sigmoid=nn.Sigmoid()

  def forward(self,features):

   out=self.linear(features)
   out=self.sigmoid(out)
   return out

In [46]:
learning_rate=0.1
epochs=25

In [47]:
loss_function=nn.BCELoss()

In [48]:
model=SimpleNN(X_train_ten.shape[1])
model.linear.weight

Parameter containing:
tensor([[-0.1416, -0.0310, -0.1339,  0.1176, -0.1142,  0.0352,  0.0593,  0.1647,
          0.0886, -0.0259, -0.0219, -0.1295, -0.1695, -0.1731,  0.1240, -0.0578,
         -0.1296, -0.1494, -0.1523, -0.0868, -0.1268, -0.1337, -0.0443,  0.0126,
         -0.0789,  0.0755, -0.0584, -0.0386,  0.0519,  0.0139]],
       requires_grad=True)

In [49]:
model.linear.bias

Parameter containing:
tensor([-0.0665], requires_grad=True)

In [53]:
#Training

optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:
    # Forward Propagation
    y_pred = model(batch_features)

    # Loss Calculation
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

     # Reset Gradients
    optimizer.zero_grad()
    # Backpropagation
    loss.backward()

    # Gradient Descent
    optimizer.step()


    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 0.1465
Epoch: 1, Loss: 0.1698
Epoch: 1, Loss: 0.1570
Epoch: 1, Loss: 0.1425
Epoch: 1, Loss: 0.1856
Epoch: 1, Loss: 0.1440
Epoch: 1, Loss: 0.1959
Epoch: 1, Loss: 0.1903
Epoch: 1, Loss: 0.2259
Epoch: 1, Loss: 0.1366
Epoch: 1, Loss: 0.1112
Epoch: 1, Loss: 0.1491
Epoch: 1, Loss: 0.1041
Epoch: 1, Loss: 0.1638
Epoch: 1, Loss: 0.1306
Epoch: 2, Loss: 0.1336
Epoch: 2, Loss: 0.1249
Epoch: 2, Loss: 0.1532
Epoch: 2, Loss: 0.1437
Epoch: 2, Loss: 0.1120
Epoch: 2, Loss: 0.1629
Epoch: 2, Loss: 0.1204
Epoch: 2, Loss: 0.1073
Epoch: 2, Loss: 0.0867
Epoch: 2, Loss: 0.1109
Epoch: 2, Loss: 0.2751
Epoch: 2, Loss: 0.1330
Epoch: 2, Loss: 0.1635
Epoch: 2, Loss: 0.1019
Epoch: 2, Loss: 0.0736
Epoch: 3, Loss: 0.0893
Epoch: 3, Loss: 0.0727
Epoch: 3, Loss: 0.1516
Epoch: 3, Loss: 0.1269
Epoch: 3, Loss: 0.1274
Epoch: 3, Loss: 0.1564
Epoch: 3, Loss: 0.1158
Epoch: 3, Loss: 0.1285
Epoch: 3, Loss: 0.1551
Epoch: 3, Loss: 0.0976
Epoch: 3, Loss: 0.0963
Epoch: 3, Loss: 0.1368
Epoch: 3, Loss: 0.1839
Epoch: 3, Loss: 0.0842
Epoch: 3, Loss: 0.1927
Epoch: 4, Loss: 0.0981
Epoch: 4, Loss: 0.1213
Epoch: 4, Loss: 0.1466
Epoch: 4, Loss: 0.1097
Epoch: 4, Loss: 0.1983
Epoch: 4, Loss: 0.0943
Epoch: 4, Loss: 0.0772
Epoch: 4, Loss: 0.1315
Epoch: 4, Loss: 0.1203
Epoch: 4, Loss: 0.0723
Epoch: 4, Loss: 0.1349
Epoch: 4, Loss: 0.1078
Epoch: 4, Loss: 0.0699
Epoch: 4, Loss: 0.0913
Epoch: 4, Loss: 0.3140
Epoch: 5, Loss: 0.0677
Epoch: 5, Loss: 0.0721
Epoch: 5, Loss: 0.0843
Epoch: 5, Loss: 0.1155
Epoch: 5, Loss: 0.1069
Epoch: 5, Loss: 0.1005
Epoch: 5, Loss: 0.0799
Epoch: 5, Loss: 0.1260
Epoch: 5, Loss: 0.1921
Epoch: 5, Loss: 0.1053
Epoch: 5, Loss: 0.0890
Epoch: 5, Loss: 0.1614
Epoch: 5, Loss: 0.1308
Epoch: 5, Loss: 0.1172
Epoch: 5, Loss: 0.0322
Epoch: 6, Loss: 0.1319
Epoch: 6, Loss: 0.1046
Epoch: 6, Loss: 0.1302
Epoch: 6, Loss: 0.0808
Epoch: 6, Loss: 0.1130
Epoch: 6, Loss: 0.0884
Epoch: 6, Loss: 0.0739
Epoch: 6, Loss: 0.0610
Epoch: 6, Loss: 0.1001
Epoch: 6, Loss: 0.0928
Epoch: 6, Loss: 0.0826
Epoch: 6, Loss: 0.1848
Epoch: 6, Loss: 0.0419
Epoch: 6, Loss: 0.1948
Epoch: 6, Loss: 0.0227
Epoch: 7, Loss: 0.0973
Epoch: 7, Loss: 0.0983
Epoch: 7, Loss: 0.1052
Epoch: 7, Loss: 0.0665
Epoch: 7, Loss: 0.0790
Epoch: 7, Loss: 0.0773
Epoch: 7, Loss: 0.0534
Epoch: 7, Loss: 0.0430
Epoch: 7, Loss: 0.1876
Epoch: 7, Loss: 0.1101
Epoch: 7, Loss: 0.0659
Epoch: 7, Loss: 0.2477
Epoch: 7, Loss: 0.0879
Epoch: 7, Loss: 0.0859
Epoch: 7, Loss: 0.1223
Epoch: 8, Loss: 0.0966
Epoch: 8, Loss: 0.0372
Epoch: 8, Loss: 0.0514
Epoch: 8, Loss: 0.1153
Epoch: 8, Loss: 0.0981
Epoch: 8, Loss: 0.1237
Epoch: 8, Loss: 0.0911
Epoch: 8, Loss: 0.0985
Epoch: 8, Loss: 0.1496
Epoch: 8, Loss: 0.1112
Epoch: 8, Loss: 0.0779
Epoch: 8, Loss: 0.1947
Epoch: 8, Loss: 0.0896
Epoch: 8, Loss: 0.0412
Epoch: 8, Loss: 0.0417
Epoch: 9, Loss: 0.1043
Epoch: 9, Loss: 0.0873
Epoch: 9, Loss: 0.0771
Epoch: 9, Loss: 0.0859
Epoch: 9, Loss: 0.1034
Epoch: 9, Loss: 0.1476
Epoch: 9, Loss: 0.0880
Epoch: 9, Loss: 0.1791
Epoch: 9, Loss: 0.1360
Epoch: 9, Loss: 0.0780
Epoch: 9, Loss: 0.0498
Epoch: 9, Loss: 0.0503
Epoch: 9, Loss: 0.1180
Epoch: 9, Loss: 0.0375
Epoch: 9, Loss: 0.0246
Epoch: 10, Loss: 0.2182
Epoch: 10, Loss: 0.1109
Epoch: 10, Loss: 0.0475
Epoch: 10, Loss: 0.0659
Epoch: 10, Loss: 0.0606
Epoch: 10, Loss: 0.0799
Epoch: 10, Loss: 0.0607
Epoch: 10, Loss: 0.0984
Epoch: 10, Loss: 0.0838
Epoch: 10, Loss: 0.0501
Epoch: 10, Loss: 0.1488
Epoch: 10, Loss: 0.0622
Epoch: 10, Loss: 0.0954
Epoch: 10, Loss: 0.1203
Epoch: 10, Loss: 0.0501
Epoch: 11, Loss: 0.0802
Epoch: 11, Loss: 0.1387
Epoch: 11, Loss: 0.2064
Epoch: 11, Loss: 0.1301
Epoch: 11, Loss: 0.0531
Epoch: 11, Loss: 0.0935
Epoch: 11, Loss: 0.0679
Epoch: 11, Loss: 0.1146
Epoch: 11, Loss: 0.0490
Epoch: 11, Loss: 0.0870
Epoch: 11, Loss: 0.0850
Epoch: 11, Loss: 0.0477
Epoch: 11, Loss: 0.0490
Epoch: 11, Loss: 0.0488
Epoch: 11, Loss: 0.1452
Epoch: 12, Loss: 0.1073
Epoch: 12, Loss: 0.0762
Epoch: 12, Loss: 0.0798
Epoch: 12, Loss: 0.0530
Epoch: 12, Loss: 0.1871
Epoch: 12, Loss: 0.0273
Epoch: 12, Loss: 0.0627
Epoch: 12, Loss: 0.1228
Epoch: 12, Loss: 0.0822
Epoch: 12, Loss: 0.0864
Epoch: 12, Loss: 0.1632
Epoch: 12, Loss: 0.0490
Epoch: 12, Loss: 0.0597
Epoch: 12, Loss: 0.0976
Epoch: 12, Loss: 0.0213
Epoch: 13, Loss: 0.0990
Epoch: 13, Loss: 0.0155
Epoch: 13, Loss: 0.1095
Epoch: 13, Loss: 0.0271
Epoch: 13, Loss: 0.1294
Epoch: 13, Loss: 0.0683
Epoch: 13, Loss: 0.2153
Epoch: 13, Loss: 0.0725
Epoch: 13, Loss: 0.0882
Epoch: 13, Loss: 0.1235
Epoch: 13, Loss: 0.1381
Epoch: 13, Loss: 0.0371
Epoch: 13, Loss: 0.1068
Epoch: 13, Loss: 0.0051
Epoch: 13, Loss: 0.0106
Epoch: 14, Loss: 0.1031
Epoch: 14, Loss: 0.1261
Epoch: 14, Loss: 0.0980
Epoch: 14, Loss: 0.2400
Epoch: 14, Loss: 0.0639
Epoch: 14, Loss: 0.0524
Epoch: 14, Loss: 0.0735
Epoch: 14, Loss: 0.0718
Epoch: 14, Loss: 0.0702
Epoch: 14, Loss: 0.0758
Epoch: 14, Loss: 0.0407
Epoch: 14, Loss: 0.0981
Epoch: 14, Loss: 0.0575
Epoch: 14, Loss: 0.0466
Epoch: 14, Loss: 0.0044
Epoch: 15, Loss: 0.0862
Epoch: 15, Loss: 0.0480
Epoch: 15, Loss: 0.0537
Epoch: 15, Loss: 0.0648
Epoch: 15, Loss: 0.0309
Epoch: 15, Loss: 0.0696
Epoch: 15, Loss: 0.1173
Epoch: 15, Loss: 0.0638
Epoch: 15, Loss: 0.0538
Epoch: 15, Loss: 0.0592
Epoch: 15, Loss: 0.1133
Epoch: 15, Loss: 0.2576
Epoch: 15, Loss: 0.1236
Epoch: 15, Loss: 0.0461
Epoch: 15, Loss: 0.0463
Epoch: 16, Loss: 0.0385
Epoch: 16, Loss: 0.0871
Epoch: 16, Loss: 0.1233
Epoch: 16, Loss: 0.1104
Epoch: 16, Loss: 0.0281
Epoch: 16, Loss: 0.0557
Epoch: 16, Loss: 0.0705
Epoch: 16, Loss: 0.0904
Epoch: 16, Loss: 0.0998
Epoch: 16, Loss: 0.0399
Epoch: 16, Loss: 0.0359
Epoch: 16, Loss: 0.0639
Epoch: 16, Loss: 0.2117
Epoch: 16, Loss: 0.0670
Epoch: 16, Loss: 0.2763
Epoch: 17, Loss: 0.0301
Epoch: 17, Loss: 0.0409
Epoch: 17, Loss: 0.0870
Epoch: 17, Loss: 0.0605
Epoch: 17, Loss: 0.0666
Epoch: 17, Loss: 0.1882
Epoch: 17, Loss: 0.0241
Epoch: 17, Loss: 0.1365
Epoch: 17, Loss: 0.1060
Epoch: 17, Loss: 0.0774
Epoch: 17, Loss: 0.0879
Epoch: 17, Loss: 0.0632
Epoch: 17, Loss: 0.0935
Epoch: 17, Loss: 0.0829
Epoch: 17, Loss: 0.0982
Epoch: 18, Loss: 0.1309
Epoch: 18, Loss: 0.1237
Epoch: 18, Loss: 0.0220
Epoch: 18, Loss: 0.0604
Epoch: 18, Loss: 0.1360
Epoch: 18, Loss: 0.0848
Epoch: 18, Loss: 0.0742
Epoch: 18, Loss: 0.0268
Epoch: 18, Loss: 0.0455
Epoch: 18, Loss: 0.0595
Epoch: 18, Loss: 0.0649
Epoch: 18, Loss: 0.0503
Epoch: 18, Loss: 0.1973
Epoch: 18, Loss: 0.0660
Epoch: 18, Loss: 0.0398
Epoch: 19, Loss: 0.0713
Epoch: 19, Loss: 0.0317
Epoch: 19, Loss: 0.0727
Epoch: 19, Loss: 0.0425
Epoch: 19, Loss: 0.1072
Epoch: 19, Loss: 0.0754
Epoch: 19, Loss: 0.0975
Epoch: 19, Loss: 0.0930
Epoch: 19, Loss: 0.0547
Epoch: 19, Loss: 0.0934
Epoch: 19, Loss: 0.0234
Epoch: 19, Loss: 0.1015
Epoch: 19, Loss: 0.0532
Epoch: 19, Loss: 0.0789
Epoch: 19, Loss: 0.6492
Epoch: 20, Loss: 0.0292
Epoch: 20, Loss: 0.0767
Epoch: 20, Loss: 0.0527
Epoch: 20, Loss: 0.1790
Epoch: 20, Loss: 0.0772
Epoch: 20, Loss: 0.0850
Epoch: 20, Loss: 0.1661
Epoch: 20, Loss: 0.0922
Epoch: 20, Loss: 0.0302
Epoch: 20, Loss: 0.0850
Epoch: 20, Loss: 0.0603
Epoch: 20, Loss: 0.0598
Epoch: 20, Loss: 0.0619
Epoch: 20, Loss: 0.0339
Epoch: 20, Loss: 0.1953
Epoch: 21, Loss: 0.0891
Epoch: 21, Loss: 0.0342
Epoch: 21, Loss: 0.0811
Epoch: 21, Loss: 0.1334
Epoch: 21, Loss: 0.0925
Epoch: 21, Loss: 0.0236
Epoch: 21, Loss: 0.1810
Epoch: 21, Loss: 0.0558
Epoch: 21, Loss: 0.0692
Epoch: 21, Loss: 0.0687
Epoch: 21, Loss: 0.0689
Epoch: 21, Loss: 0.0625
Epoch: 21, Loss: 0.0987
Epoch: 21, Loss: 0.0538
Epoch: 21, Loss: 0.0342
Epoch: 22, Loss: 0.0491
Epoch: 22, Loss: 0.1428
Epoch: 22, Loss: 0.0954
Epoch: 22, Loss: 0.0811
Epoch: 22, Loss: 0.0425
Epoch: 22, Loss: 0.0573
Epoch: 22, Loss: 0.0479
Epoch: 22, Loss: 0.0613
Epoch: 22, Loss: 0.1621
Epoch: 22, Loss: 0.1638
Epoch: 22, Loss: 0.0455
Epoch: 22, Loss: 0.0349
Epoch: 22, Loss: 0.0495
Epoch: 22, Loss: 0.0580
Epoch: 22, Loss: 0.0800
Epoch: 23, Loss: 0.0825
Epoch: 23, Loss: 0.0828
Epoch: 23, Loss: 0.0940
Epoch: 23, Loss: 0.0481
Epoch: 23, Loss: 0.0980
Epoch: 23, Loss: 0.0583
Epoch: 23, Loss: 0.0755
Epoch: 23, Loss: 0.0654
Epoch: 23, Loss: 0.0787
Epoch: 23, Loss: 0.0540
Epoch: 23, Loss: 0.1746
Epoch: 23, Loss: 0.0764
Epoch: 23, Loss: 0.0645
Epoch: 23, Loss: 0.0423
Epoch: 23, Loss: 0.0179
Epoch: 24, Loss: 0.1263
Epoch: 24, Loss: 0.0437
Epoch: 24, Loss: 0.0548
Epoch: 24, Loss: 0.0618
Epoch: 24, Loss: 0.2117
Epoch: 24, Loss: 0.0483
Epoch: 24, Loss: 0.1149
Epoch: 24, Loss: 0.0635
Epoch: 24, Loss: 0.0510
Epoch: 24, Loss: 0.0365
Epoch: 24, Loss: 0.1130
Epoch: 24, Loss: 0.0348
Epoch: 24, Loss: 0.0846
Epoch: 24, Loss: 0.0395
Epoch: 24, Loss: 0.0163
Epoch: 25, Loss: 0.1232
Epoch: 25, Loss: 0.0321
Epoch: 25, Loss: 0.0405
Epoch: 25, Loss: 0.0677
Epoch: 25, Loss: 0.0859
Epoch: 25, Loss: 0.1036
Epoch: 25, Loss: 0.0529
Epoch: 25, Loss: 0.2360
Epoch: 25, Loss: 0.0264
Epoch: 25, Loss: 0.0601
Epoch: 25, Loss: 0.0392
Epoch: 25, Loss: 0.0238
Epoch: 25, Loss: 0.1286
Epoch: 25, Loss: 0.0536
Epoch: 25, Loss: 0.0251

In [58]:
#evaluation

with torch.no_grad():
  y_pred=model.forward(X_test_ten)
  y_pred=(y_pred > 0.7).float()
  accuracy=(y_pred==y_test_ten).float().mean()



  print(y_pred)

tensor([[1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [59]:
  print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.5184672474861145