In [274]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [275]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [276]:
df.shape

(569, 33)

In [277]:

df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [278]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [279]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [280]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [281]:
X_train

array([[-0.80556848,  0.12501093, -0.74322259, ..., -0.31019821,
         0.11753332, -0.78024521],
       [-0.52829799,  0.68996083, -0.56181578, ..., -0.76213148,
         0.36327126, -0.08996388],
       [ 1.82149935, -0.46955327,  1.74115577, ...,  1.48084717,
        -0.33326869, -0.75365145],
       ...,
       [-1.23183684, -1.69513005, -1.25083624, ..., -1.72319132,
         0.37174498, -0.12002639],
       [ 0.13547075,  1.04988858,  0.10483388, ..., -0.66943889,
        -0.61629101, -0.64322957],
       [-0.34905243, -1.20763296, -0.28645165, ...,  0.64494508,
        -0.41800591,  1.97798946]])

In [282]:
y_train

288    B
490    B
373    M
493    B
290    B
      ..
481    B
36     M
140    B
90     B
247    B
Name: diagnosis, Length: 455, dtype: object

In [283]:
X_test

array([[ 0.23909709,  0.61478604,  0.22522942, ...,  0.26112797,
         0.47004015,  0.51591118],
       [ 0.11026434, -0.01622654,  0.09181814, ..., -0.26772043,
        -0.70272297, -0.51777643],
       [ 1.5274246 ,  1.27313491,  1.45236916, ...,  0.50082403,
        -1.00438748, -1.31096401],
       ...,
       [-1.01562188,  0.83803237, -1.02265414, ..., -1.24910892,
        -1.11624061, -0.91437022],
       [ 2.27801541,  0.05894825,  2.47329085, ...,  2.69146399,
         1.98175216,  0.82694247],
       [-0.51429443, -0.79986671, -0.53537757, ..., -0.99272516,
        -0.68408079, -1.18666713]])

In [284]:
y_test

413    B
448    B
451    M
533    M
114    B
      ..
563    M
417    M
299    B
108    M
189    B
Name: diagnosis, Length: 114, dtype: object

In [285]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [286]:
X_train_ten=torch.from_numpy(X_train)
X_test_ten=torch.from_numpy(X_test)
y_train_ten=torch.from_numpy(y_train)
y_test_ten=torch.from_numpy(y_test)

In [287]:
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_train_ten:", X_train_ten.shape)
print("y_train_ten:", y_train_ten.shape)

X_train: (455, 30)
y_train: (455,)
X_train_ten: torch.Size([455, 30])
y_train_ten: torch.Size([455])

In [288]:
X_train_ten = X_train_ten.float()
X_test_ten = X_test_ten.float()

y_train_ten = y_train_ten.float()
y_test_ten = y_test_ten.float()

In [289]:
import torch
import torch.nn as nn

# Defining Neural Network
class SimpleNN(nn.Module):

  def __init__(self,num_features):

   super().__init__()
   self.linear=nn.Linear(num_features,1)
   self.sigmoid=nn.Sigmoid()

  def forward(self,features):

   out=self.linear(features)
   out=self.sigmoid(out)
   return out

In [290]:
learning_rate=0.1
epochs=25

In [291]:
loss_function=nn.BCELoss()

In [292]:
model=SimpleNN(X_train_ten.shape[1])
model.linear.weight

Parameter containing:
tensor([[-0.1423, -0.0058,  0.1096, -0.0012, -0.0259,  0.0367,  0.1502, -0.0005,
         -0.0003,  0.1033,  0.0413,  0.0420, -0.1633, -0.0404, -0.0752, -0.0880,
         -0.0455,  0.0708, -0.0284, -0.0193,  0.1352,  0.0779,  0.0639, -0.1340,
         -0.1018,  0.0014,  0.0150, -0.1454,  0.0761,  0.1784]],
       requires_grad=True)

In [293]:
model.linear.bias

Parameter containing:
tensor([0.0129], requires_grad=True)

In [294]:
#Training

optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):

    # Forward Propagation
    y_pred = model(X_train_ten)

    # Loss Calculation
    loss = loss_function(y_pred, y_train_ten.float().view(-1, 1))

     # Reset Gradients
    optimizer.zero_grad()
    # Backpropagation
    loss.backward()

    # Gradient Descent
    optimizer.step()


    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 0.6970
Epoch: 2, Loss: 0.5290
Epoch: 3, Loss: 0.4405
Epoch: 4, Loss: 0.3863
Epoch: 5, Loss: 0.3489
Epoch: 6, Loss: 0.3212
Epoch: 7, Loss: 0.2994
Epoch: 8, Loss: 0.2818
Epoch: 9, Loss: 0.2671
Epoch: 10, Loss: 0.2547
Epoch: 11, Loss: 0.2439
Epoch: 12, Loss: 0.2345
Epoch: 13, Loss: 0.2262
Epoch: 14, Loss: 0.2188
Epoch: 15, Loss: 0.2121
Epoch: 16, Loss: 0.2061
Epoch: 17, Loss: 0.2006
Epoch: 18, Loss: 0.1956
Epoch: 19, Loss: 0.1910
Epoch: 20, Loss: 0.1867
Epoch: 21, Loss: 0.1828
Epoch: 22, Loss: 0.1791
Epoch: 23, Loss: 0.1757
Epoch: 24, Loss: 0.1725
Epoch: 25, Loss: 0.1695

In [295]:
#evaluation

with torch.no_grad():
  y_pred=model.forward(X_test_ten)
  y_pred=(y_pred > 0.8).float()
  accuracy=(y_pred==y_test_ten).float().mean()



  print(y_pred)

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.]])

In [296]:
  print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.5554016828536987